### PR TITLE
Initial fix for #36. Restructured logic behind favorites.

### PR DESCRIPTION
**Pull request by antonshevchenko**
See #36.

### CODE REVIEW

**Comment by rvanbaalen** [comment]
So basically everything @thoughtpalette made has ben refactored? ;-)

**Comment by thoughtpalette** [comment]
Will definitely need updates where the code has been referenced. I'll take a look at this later :man:

**Comment by antonshevchenko** [comment]
That's why I think it's best to leave it as is.

**Comment by rvanbaalen** [comment]
But leaving 'as is' would mean the app functions shitty? I'd say
@thoughtpallet comes out of his cave and helps us out on this one?

------------------------------------------
Neverwoods
Margrietlaan 10
Willemstad, Curaçao
T (+599 9) 522 9996
W http://www.neverwoods.com

"we create the future"

**Comment by antonshevchenko** [comment]
If we can get this in the book on time I'm all for it. Otherwise, we should leave it out.

**Comment by rvanbaalen** [comment]
Like I said, it's up to Chris to deliver in time.

------------------------------------------
Neverwoods
Margrietlaan 10
Willemstad, Curaçao
T (+599 9) 522 9996
W http://www.neverwoods.com

"we create the future"

**Comment by thoughtpalette** [comment]
I have another contracted project with a Weds deadline. I won't be able to get to anything major until then. If the changes are minor it's not a big deal. 

Have not built the app in awhile so I'll have to see what "app functions shitty" means.

**Comment by rvanbaalen** [comment]
We all have contracted projects with deadlines Chris yet most of us are able to put a significant amount of time and effort in this project. It's unfortunate that you somehow aren't able to do the same. 

---
This email was sent from my iPhone and therefore subject to typos and other inaccuracies.

**Comment by thoughtpalette** [comment]
It is unfortunate. My priorities are clearly different.

**Comment by thoughtpalette** [comment]
At this point I'd be fine with being cut out entirely due to apathy and lack of commitment/effort. Let me know what you think @rvanbaalen @keithdmoore

**Comment by keithdmoore** [comment]
@thoughtpalette I would be ok with that, all things considered.

**Comment by rvanbaalen** [comment]
Same here. You should probably send an e-mail to Troy / Christina / the
whole team about it.

------------------------------------------
Neverwoods
Margrietlaan 10
Willemstad, Curaçao
T (+599 9) 522 9996
W http://www.neverwoods.com

"we create the future"

**Comment by thoughtpalette** [comment]
AfterI get a response from Troy I'll send out an email if necessary.

**Comment by keithdmoore** [comment]
:+1: to merge.  I added a couple of fixes too.

**Comment by rvanbaalen** [comment]
Go ahead, green light here.

------------------------------------------
Neverwoods
Margrietlaan 10
Willemstad, Curaçao
T (+599 9) 522 9996
W http://www.neverwoods.com

"we create the future"

**Pull request merged**
