### PR TITLE
Code restructuring + template enhancements

### PR DESCRIPTION
**Pull request by antonshevchenko**
- Moved all popups and modals into their own directories
- Improved the favorite template and add favorite modal
- Updated login modal
- Add favorite modal includes form that validates user input
- Switched to Ionicons 2.0 (up-to-date icons)
- Overhaul of `.vertical-center` class

### CODE REVIEW

**Comment by antonshevchenko** [comment]
To fix:

- Removing favorites
- After creation of favorite, sometimes the location coordinates are innacurate

**Comment by keithdmoore** [comment]
I will fix the remove favorites problem.

**Comment by troymott** [comment]
Thank you!

--Troy

**Comment by keithdmoore** [comment]
@antonshevchenko @rvanbaalen we ready to merge this PR?

**Comment by antonshevchenko** [comment]
@keithdmoore Once we fix that bug, it should be all good!

**Comment by keithdmoore** [comment]
@antonshevchenko Can you test my fixes to see if both issues are resolved?

**Comment by rvanbaalen** [comment]
Looks good to me. Merge when youre ready. 

---
This email was sent from my iPhone and therefore subject to typos and other inaccuracies.

**Comment by antonshevchenko** [comment]
@keithdmoore Checked out the removal of favorites. Works flawlessly! :+1:

**Comment by rvanbaalen** [comment]
Can confirm! Great work. 

---
This email was sent from my iPhone and therefore subject to typos and other inaccuracies.

**Comment by rvanbaalen** [comment]
Awesome. I suppose trendicity is almost a wrap now?

---
This email was sent from my iPhone and therefore subject to typos and other inaccuracies.

**Comment by keithdmoore** [comment]
I am having issues running it on the iPhone 6 simulator.  Seems like that was working before.  Anton must not have had issues since he was able to get screenshots.

**Pull request merged**
